units_files_to_cover:
  - app/models
functionals_files_to_cover:
  - app/controllers
  - app/helpers
units_files_to_test:
  - unit
functionals_files_to_test:
  - functional
  - integration
before_rcov: db:test:prepare
